<?php
/*
DB details defined here
*/

$DBINFO["USERNAME"] = "root";
$DBINFO["PASSWORD"] = "root";

$DBNAME["LMS"] = "v_productivity";

$TABLEINFO["USERS"] = "p_users";

$TABLEINFO["WORKERS"] = "p_workers";
$TABLEINFO["WORKERTEAM"] = "p_workerteam";

$TABLEINFO["SCAFFOLDTYPE"] = "p_scaffoldtype";

$TABLEINFO["PROJECTS"] = "p_projects";

$TABLEINFO["CONTRACTS"] = "p_contracts";

$TABLEINFO["CLIENTS"] = "p_clients";

?>



